<?php
/*
 * Copyright (c) 2017-2025 Aimy Extensions, Netzum Sorglos Software GmbH
 * Copyright (c) 2014-2017 Aimy Extensions, Lingua-Systems Software GmbH
 *
 * https://www.aimy-extensions.com/
 *
 * License: GNU GPLv2, see LICENSE.txt within distribution and/or
 *          https://www.aimy-extensions.com/software-license.html
 */
 defined( '_JEXEC' ) or die(); require_once( JPATH_COMPONENT . '/helpers/rights.php' ); require_once( JPATH_COMPONENT . '/helpers/config.php' ); require_once( JPATH_COMPONENT . '/helpers/message.php' ); use Joomla\CMS\MVC\View\HtmlView; use Joomla\CMS\Language\Text; use Joomla\CMS\Router\Route; use Joomla\CMS\Uri\Uri; use Joomla\CMS\Factory; use Joomla\CMS\Toolbar\ToolbarHelper; class AimySitemapViewNotify extends HtmlView { protected $allow_notify = false; protected $allow_config = false; protected $ping_cfg = null; protected $has_sitemap_xml = false; protected $show_sitemap_field_hint = false; public function display( $tpl = null ) { $errors = $this->get( 'Errors' ); if ( is_array( $errors ) && count( $errors ) ) { throw new Exception( implode( "\n", $errors ), 500 ); return false; } $rights = AimySitemapRightsHelper::getRights(); $this->allow_notify = $rights->get( 'aimysitemap.notify' ); $this->allow_config = $rights->get( 'core.admin' ); $this->set_has_sitemap_xml(); if ( ! $this->has_sitemap_xml ) { $msg = new AimySitemapMessageHelper(); $msg->error( Text::_( 'AIMY_SM_WARN_XML_SITEMAP_MISSING' ) . ' &rarr; ' . sprintf( '<a href="%s">%s &amp; %s</a>', Route::_( 'index.php?option=com_aimysitemap&view=urls' ), Text::_( 'AIMY_SM_LINK_MANAGE' ), Text::_( 'AIMY_SM_WRITE_LBL' ) ) ); } if ( Uri::root( true ) == '' ) { $path = JPATH_ROOT . '/robots.txt'; $hint = false; if ( file_exists( $path ) ) { $s = file_get_contents( $path ); if ( $s !== false ) { $this->show_sitemap_field_hint = ( empty( $s ) or ! preg_match( '#^Sitemap:#mi', $s ) ); } } else { $this->show_sitemap_field_hint = true; } } if ( $this->allow_notify ) { Factory::getDocument()->addScript( Uri::root( true ) . '/media/com_aimysitemap/ping.js' . '?r=39.0' ); $this->set_ping_cfg(); if ( $this->ping_cfg[ 'ses' ][ 'indexnow' ] ) { require_once( JPATH_COMPONENT. '/IndexNow.php' ); try { AimySitemapIndexNow::load(); } catch ( Exception $e ) { $msg = new AimySitemapMessageHelper(); $msg->error( $e->getMessage() ); } } } else { $msg = new AimySitemapMessageHelper(); $msg->error( Text::_( 'JLIB_APPLICATION_ERROR_ACCESS_FORBIDDEN' ) ); } $this->addToolbar(); parent::display( $tpl ); } private function set_ping_cfg() { $cfg = new AimySitemapConfigHelper(); $this->ping_cfg = array( 'ses' => array( 'indexnow' => $cfg->get( 'notify_indexnow' ) ), 'url' => Uri::root() . $cfg->get( 'xml_path' ) ); } private function set_has_sitemap_xml() { $cfg = new AimySitemapConfigHelper(); $this->has_sitemap_xml = is_file( JPATH_ROOT . '/' . $cfg->get( 'xml_path' ) ); } protected function addToolbar() { ToolBarHelper::title( Text::_( 'AIMY_SM_NOTIFY' ), '' ); if ( $this->allow_notify ) { ToolBarHelper::custom( 'notify.ping', 'tree-2', Text::_( 'AIMY_SM_NOTIFY_DSC' ), Text::_( 'AIMY_SM_NOTIFY_LBL' ), false ); } if ( $this->allow_config ) { ToolBarHelper::preferences( 'com_aimysitemap' ); } } } 
