<?php
/*
 * Copyright (c) 2018-2025 Aimy Extensions, Netzum Sorglos Software GmbH
 *
 * https://www.aimy-extensions.com/
 *
 * License: GNU GPLv2, see LICENSE.txt within distribution and/or
 *          https://www.aimy-extensions.com/software-license.html
 */
 defined( '_JEXEC' ) or die(); use Joomla\CMS\Factory; use Joomla\CMS\HTML\HTMLHelper; abstract class AimySitemapCompatHelper { static public function getJoomlaMajorVersion() { return substr( strVal( JVERSION ), 0, 1 ); } static public function isJoomla3() { return ( self::getJoomlaMajorVersion() == '3' ); } static public function getKnownLanguages() { if ( self::isJoomla3() ) { $jlang = Factory::getLanguage(); return $jlang->getKnownLanguages(); } require_once( JPATH_ROOT . '/libraries/src/Language/LanguageHelper.php' ); return Joomla\CMS\Language\LanguageHelper::getKnownLanguages(); } static public function getJHtmlBootstrapMethodName( $s ) { if ( self::isJoomla3() ) { return 'bootstrap.' . $s; } switch ( $s ) { case 'startPane': return 'bootstrap.startTabSet'; case 'endPane': return 'bootstrap.endTabSet'; case 'addPanel': return 'bootstrap.addTab'; case 'endPanel': return 'bootstrap.endTab'; } } static public function addInlineJavascript( $s ) { return Factory::getDocument()->addScriptDeclaration( $s ); } static public function loadFramework( $s ) { $n = $s; switch ( $s ) { case 'jquery': $n = 'jquery.framework'; break; } return HTMLHelper::_( $n ); } static public function getMenuItemParam( $mi, $p, $dflt = false ) { if ( ! $mi ) { return $dflt; } if ( method_exists( $mi, 'getParams' ) ) { return $mi->getParams()->get( $p, $dflt ); } if ( isset( $mi->params ) && method_exists( $mi->params, 'get' ) ) { return $mi->params->get( $p, $dflt ); } return $dflt; } static public function getCliPluginData() { $db = Factory::getDbo(); $q = $db->getQuery( true ); $q->select( $db->quoteName( array( 'manifest_cache', 'enabled' ) ) ) ->from( '#__extensions' ) ->where( $db->quoteName( 'element' ) . ' = ' . $db->quote( 'aimysitemapcli' ) . ' AND ' . $db->quoteName( 'type' ) . ' = ' . $db->quote( 'plugin' ) ); $db->setQuery( $q ); $v = $db->loadAssoc(); if ( empty( $v ) ) { return false; } $o = new \StdClass(); $o->manifest = json_decode( $v[ 'manifest_cache' ] ); $o->enabled = boolVal( $v[ 'enabled' ] ); return $o; } } 
